language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - "node"
env:
    - NODE_ENV=TEST
cache:
    yarn: true
    directories:
        - "node_modules"
script:
    - yarn build
    - yarn coveralls

    # types are only tested in node 10
    - yarn global add if-node-version
    - if-node-version "10" || travis_terminate 0
    - yarn test:flow

    # typescript@2.8.1
    - yarn test:dts

    # typescript@latest
    - yarn add typescript@latest -D
    - yarn test:dts
jobs:
    include:
        - stage: deploy
          if: branch == master && !fork
          node_js: "8.9.1" # pre-installed version
          script:
              - yarn build
              - yarn global add semantic-release@^15
              - semantic-release
