language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - "node"
env:
    - NODE_ENV=TEST
cache:
    yarn: true
    directories:
        - "node_modules"
script:
    - yarn build
    - yarn coveralls
    - yarn test:flow
jobs:
    include:
        - stage: deploy
          node_js: "8.9.1" # pre-installed version
          script:
              - yarn build
              - yarn global add semantic-release@^15
              - semantic-release
