language: node_js
node_js:
  - "8"
  - "10"
  # - "node"
env:
  - NODE_ENV=TEST
cache:
  yarn: true
#  directories:
#    - "node_modules"
before_script:
  - yarn global add if-node-version
script:
  - yarn build || travis_terminate 1
  - if-node-version 10 || { yarn test && travis_terminate 0; }
  - yarn coveralls
jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: "10.18" # pre-installed version
      script:
        - NODE_ENV= yarn build
        - yarn semantic-release
